title: MedData Engineering Hub
description: A premier data engineering hub providing comprehensive datasets for machine learning and data science research
baseurl: "/MedData"
url: "https://alaamer12.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  datasets:
    output: true
    permalink: /dataset/:path/
  datasets_collection:
    output: true
    permalink: /dataset/:name/
  documentation:
    output: true
    permalink: /docs/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "datasets_collection"
    values:
      layout: "dataset" 
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "documentation"
  - scope:
      path: "dataset/*/docs.html"
    values:
      layout: "documentation" 